# test
# ref: https://qiita.com/hkusu/items/39eb92dbd4d6db8a14d8
# ref: https://zenn.dev/snowcait/articles/d6bc5eafd8ab75
# ref: https://github.com/actions/github-script
name: Auto assign pull requests

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write
  issues: read

jobs:
  assign:
    name: Assign assignees and reviewers
    runs-on: ubuntu-latest
    steps:
      - name: Assign Pull Request Author as Assignee
        uses: actions/github-script@v6
        if: ${{ toJSON(github.event.pull_request.assignees) == '[]' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { number: issue_number, user } = context.payload.pull_request;
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number,
              assignees: [user.login]
            });
      - name: Assign random reviewers
        uses: actions/github-script@v6
        if: ${{ toJSON(github.event.pull_request.requested_reviewers) == '[]' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const groups = {
              group1: ['takasp', 'takasp', 'takasp'],
              group2: ['takasp', 'takasp', 'takasp'],
              group3: ['takasp', 'takasp', 'takasp']
            };

            const author = context.payload.pull_request.user.login;
            const reviewers = [];
            for (const [group, members] of Object.entries(groups)) {
              const filteredMembers = members.filter(user => user !== author);
              if (filteredMembers.length > 0) {
                const randomReviewer = filteredMembers[Math.floor(Math.random() * filteredMembers.length)];
                reviewers.push(randomReviewer);
              }
            }

            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              reviewers
            });
