# test
name: Auto assign pull requests

on: push
  #pull_request:
  #  types: opened

jobs:
  assign:
    name: Set assignees and reviewers
    runs-on: ubuntu-22.04
    steps:
      - name: Set assignees
        env:
          ASSIGNEES: "${{ github.actor }}"
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const pr = await octokit.rest.pulls.get({
              owner,
              repo,
              pull_number,
            });
            console.log(pr);
            
            #        run: |
            #          assignee_count=$(cat ${{ github.event_path }} | jq '.pull_request.assignees | length')
            #          if [[ 0 == $assignee_count ]]; then
            #            assignees=$(echo "\"${ASSIGNEES// /}\"" | jq 'split(",")')
            #            curl -X POST \
            #                 -H "Content-Type: application/json" \
            #                 -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            #                 -d "{ \"assignees\": $assignees }" \
            #                 https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/assignees
            #          fi
            #      - name: Set reviewers
            #        env:
            #          REVIEWERS: "hoge, fuga, piyo" # edit here
            #        run: |
            #          reviewer_count=$(cat ${{ github.event_path }} | jq '.pull_request.requested_reviewers | length')
            #          if [[ 0 == $reviewer_count ]]; then
            #            reviewers=$(echo "\"${REVIEWERS// /}\"" | jq 'split(",") | .-["${{ github.actor }}"]')
            #            curl -X POST \
            #                 -H "Content-Type: application/json" \
            #                 -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            #                 -d "{ \"reviewers\": $reviewers }" \
            #                 https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers
            #          fi
