# test
# ref: https://qiita.com/hkusu/items/39eb92dbd4d6db8a14d8
# ref: https://zenn.dev/snowcait/articles/d6bc5eafd8ab75
# ref: https://github.com/actions/github-script
name: Auto assign pull requests

on: push
  #pull_request:
  #  types: opened

jobs:
  assign:
    name: Set assignees and reviewers
    runs-on: ubuntu-22.04
    steps:
      - name: Set assignees
        env:
          ASSIGNEES: "${{ github.actor }}"
        uses: actions/github-script@v6
        if: ${{ toJSON(github.event.pull_request.assignees) != '[]' }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log("process.env.ASSIGNEE: ", process.env.ASSIGNEE);
            console.log('sssss');
            const pr = await github.rest.pulls.get({
              owner: 'takasp',
              repo: 'github-actions-practice',
              pull_number: 4,
            });
            console.log(pr.status);
            console.log(pr);
            // console.log(JSON.stringify(pr));
            // console.log("pr.assignees", pr.assignees);
            // console.log("pr.assignees.length:", pr.assignees.length);
            if (pr.assignees.length === 0) {
              
            }
