# test
name: Auto assign pull requests

on: push
  #pull_request:
  #  types: opened

jobs:
  assign:
    name: Set assignees and reviewers
    runs-on: ubuntu-22.04
    steps:
      - name: Set assignees
        env:
          ASSIGNEES: "${{ github.actor }}"
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const pr = await octokit.rest.pulls.get({
              owner,
              repo,
              pull_number,
            });
            console.log(pr);
