name: Get Workflow Number and Completion Time

on:
#  workflow_run:
#    workflows: ["Hadolint"]
#    types:
#      - completed
  push:
    branches: [ "main" ]

jobs:
  get_workflow_info:
    runs-on: ubuntu-latest

    steps:
      - name: Get Workflow Number and Completion Time
        uses: actions/github-script@v6
        with:
          script: |

            const workflows = await github.rest.actions.listRepoWorkflows({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            
            console.log(JSON.stringify(workflows));
            
            const workflow = await github.rest.actions.getWorkflow({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: '73424475',
            });
            console.log(JSON.stringify(workflow));

#            const completedAt = new Date(runs.jobs[0].completed_at);
#            console.log(`Workflow completed at: ${completedAt.toISOString()}`);


#            const workflow = await github.rest.actions.getWorkflow({ workflow_id: github.run_id });
#            console.log(`Workflow Number: ${workflow.number}`);
#
#            const runs = await github.actions.listJobsForWorkflowRun({
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              run_id: github.run_id
#            });
