name: get-pull-request
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [ closed ]
  push:
    branches: [ "main" ]

jobs:
  summary:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Get event name merged
        id: merged
        if: github.event.pull_request.merged == true
        run: echo event='merged' >> $GITHUB_OUTPUT
      - name: Get event name workflow_dispatch
        id: workflow_dispatch
        if: github.event_name == 'workflow_dispatch'
        run: echo event='workflow_dispatch' >> $GITHUB_OUTPUT
      - name: Get event name push
        id: push
        if: github.event_name == 'push'
        run: echo event='push' >> $GITHUB_OUTPUT
      - name: echo vars
        run: |
          echo {{ steps.merged.outputs.event }}
          echo {{ steps.workflow_dispatch.outputs.event }}
          echo {{ steps.push.outputs.event }}
      - name: Get pull requests
        uses: actions/github-script@v6
        env:
          EVENT_NAME: ${{ steps.merged.outputs.event || steps.workflow_dispatch.outputs.event || steps.push.outputs.event }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const eventName = process.env.EVENT_NAME;
            const allPullRequests = [];

            if (eventName === 'workflow_dispatch') {
              const perPage = 2;
              let page = 1;
              while (true) {
                const { data } = await github.rest.pulls.list({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  state: 'closed',
                  per_page: perPage,
                  page: page
                });
  
                if (data.length === 0) {
                  break;
                }
  
                allPullRequests.push(...data);
                page++;
              }
            } else if (eventName === 'merged') {
              const { data } = await github.pulls.get({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: context.payload.pull_request.number
              });
              allPullRequests.push(...data);
            }

            const leadTimeRawList = [];

            for (const pr of allPullRequests) {
              const { data: commits } = await github.rest.pulls.listCommits({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
              });

              const sortedCommits = commits.sort((a, b) => (new Date(a.commit.author.date) - new Date(b.commit.author.date)));
              const firstCommitted = sortedCommits[0].commit.author.date;
              leadTimeRawList.push({
                number: pr.number,
                first_committed: firstCommitted,
                merged_at: pr.merged_at,
                repository: pr.head.repo.name,
                author: pr.user.login,
                base: pr.base.ref,
                head: pr.head.ref,
              });
            }
            console.log(JSON.stringify(leadTimeRawList));
