name: get-pull-request
on:
  workflow_dispatch:
    inputs:
      pr_numbers:
        description: 'Comma-separated list of Pull Request numbers'
        required: false
  pull_request:
    branches:
      - main
    types: [ closed ]

jobs:
  summary:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: GAS_URL
    steps:
      - name: Get event name merged
        id: merged
        if: github.event.pull_request.merged == true
        run: echo event='merged' >> $GITHUB_OUTPUT
      - name: Get event name workflow_dispatch
        id: workflow_dispatch
        if: github.event_name == 'workflow_dispatch'
        run: echo event='workflow_dispatch' >> $GITHUB_OUTPUT
      - name: echo vars
        run: |
          echo ${{ steps.merged.outputs.event }}
          echo ${{ steps.workflow_dispatch.outputs.event }}
      - name: Set inputs
        run: |
          echo "PR_NUMBERS=${{ github.event.inputs.pr_numbers || '' }}" >> $GITHUB_ENV
      - name: Get pull requests
        uses: actions/github-script@v6
        env:
          EVENT_NAME: ${{ steps.merged.outputs.event || steps.workflow_dispatch.outputs.event }}
          LEAD_TIME_URL: ${{ secrets.LEAD_TIME_URL }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const eventName = process.env.EVENT_NAME;
            const inputPrNumbers = process.env.PR_NUMBERS;
            const allPullRequests = [];

            if (eventName === 'workflow_dispatch' && inputPrNumbers) {
              const prNumbers = inputPrNumbers.split(',').map(Number);
              const data = await Promise.all(prNumbers.map(async prNumber => {
                const response = await github.rest.pulls.get({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  state: 'closed',
                  pull_number: prNumber
                });
                return response.data;
              }));
            
              allPullRequests.push(...data);
            } else if (eventName === 'workflow_dispatch') {
              const perPage = 2;
              let page = 1;
              while (true) {
                const { data } = await github.rest.pulls.list({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  state: 'closed',
                  per_page: perPage,
                  page: page
                });
  
                if (data.length === 0) {
                  break;
                }
  
                allPullRequests.push(...data);
                page++;
              }
            } else if (eventName === 'merged') {
              const { data } = await github.rest.pulls.get({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: context.payload.pull_request.number
              });
              allPullRequests.push(...[data]);
            }

            const leadTimeRawList = [];

            for (const pr of allPullRequests) {
              const { data: commits } = await github.rest.pulls.listCommits({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
              });

              const sortedCommits = commits.sort((a, b) => (new Date(a.commit.author.date) - new Date(b.commit.author.date)));
              const firstCommitted = sortedCommits[0].commit.author.date;
              leadTimeRawList.push({
                number: pr.number,
                first_committed: firstCommitted,
                merged_at: pr.merged_at,
                repository: pr.head.repo.name,
                author: pr.user.login,
                base: pr.base.ref,
                head: pr.head.ref,
              });
            }
            const leadTimeRawListSortedByNumber = leadTimeRawList.sort((a, b) => a.number - b.number);

            if (leadTimeRawListSortedByNumber.length) {
              const url = process.env.LEAD_TIME_URL;
              fetch(url, {
                  method: 'POST',
                  headers: {
                    'Content-Type': 'application/json',
                  },
                  body: JSON.stringify(leadTimeRawListSortedByNumber)
              }).then((response) => {
                console.log(JSON.stringify(response));
              }).catch((error) => {
                console.error(error);
              });
            }
