name: get-pull-request
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  summary:
    runs-on: ubuntu-latest
    steps:
      - name: Get pull requests
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pulls = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed',
              per_page: 10,
            });
            const pullRequests = pulls.data.map((pullRequest) => ({
              number: pullRequest.number,
              merged_at: pullRequest.merged_at,
              repository: pullRequest.head.repo.name,
              author: pullRequest.user.login,
              base: pullRequest.base.ref,
              head: pullRequest.head.ref,
            }));
            const response = await Promise.all(
              pullRequests.map((pr) => {
                return github.rest.pulls.listCommits({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: pr.number,
                });
              }),
            );
            console.log(JSON.stringify(response));
