name: get-pull-request
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  summary:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Get pull requests
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const perPage = 2; // ページごとのアイテム数
            let page = 1;
            const allPullRequests = [];

            while (true) {
              const { data } = await github.rest.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
                per_page: perPage,
                page: page
              });
            
              if (data.length === 0) {
                break;
              }
            
              allPullRequests.push(...data);
              page++;
              console.log(page);
            }

            console.log(JSON.stringify(allPullRequests));
            
            const { data: pullRequests } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed',
              per_page: 10,
            });
            
            const firstCommitHashes = [];

            for (const pr of pullRequests) {
              const { data: commits } = await github.rest.pulls.listCommits({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
              });

              const sortedCommits = commits.sort((a, b) => (new Date(a.commit.author.date) - new Date(b.commit.author.date)));
              const firstCommitHash = sortedCommits[0].sha;
              firstCommitHashes.push({
                number: pr.number,
                firstCommitHash,
                merged_at: pr.merged_at,
                repository: pr.head.repo.name,
                author: pr.user.login,
                base: pr.base.ref,
                head: pr.head.ref,
              });
            }
            console.log(JSON.stringify(firstCommitHashes));
