name: get-pull-request
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  summary:
    runs-on: ubuntu-latest
    steps:
      - name: Get pull requests
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pullRequests } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed',
              per_page: 10,
            });
            
            const firstCommitHashes = [];

            for (const pr of pullRequests) {
              const { data: commits } = await github.rest.pulls.listCommits({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
              });

              const sortedCommits = commits.sort((a, b) => (new Date(a.commit.author.date) - new Date(b.commit.author.date)));
              const firstCommitHash = sortedCommits[0].sha;
              firstCommitHashes.push({
                number: pr.number,
                firstCommitHash,
                merged_at: pullRequest.merged_at,
                repository: pullRequest.head.repo.name,
                author: pullRequest.user.login,
                base: pullRequest.base.ref,
                head: pullRequest.head.ref,
              });
            }
            console.log(JSON.stringify(firstCommitHashes));
