name: get-pull-request-by-branch
on:
  workflow_dispatch:
    inputs:
      pr_numbers:
        description: 'Comma-separated list of Pull Request numbers'
        required: false
  pull_request:
    types: [ closed ]

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    environment: GAS_URL
    defaults:
      run:
        working-directory: .github/workflows/scripts/github-interactions
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Get PR numbers by workflow_dispatch with pr_numbers # ワークフロー実行でPR番号が指定された場合はその番号を取得する
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.pr_numbers
        run: |
          echo "PR_NUMBERS=${{ github.event.inputs.pr_numbers || '-1' }}" >> $GITHUB_ENV
      - name: End job if PR is not merged
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == false
        run: exit 0
      - name: Get PR numbers by pull_request # PRがマージされた時は該当のマージされたPRの番号を取得する
        if: github.event_name == 'pull_request'
        run: |
          echo "PR_NUMBERS=${{ github.event.pull_request.number || '-1' }}" >> $GITHUB_ENV
      - name: echo input PR_NUMBERS　
        run: echo $PR_NUMBERS

      - name: Set repository owner and name as env
        run: |
          echo "GITHUB_REPO_OWNER=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 1)" >> $GITHUB_ENV
          echo "GITHUB_REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)" >> $GITHUB_ENV

      - name: Run get-pull-requests
        run: npm run start:pull-request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LEAD_TIME_URL: ${{ secrets.LEAD_TIME_URL }}
          NODE_OPTIONS: "--max_old_space_size=4096"
