name: Get Workflow Number and Completion Time

on:
  workflow_run:
    workflows: ["Hadolint"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      run_ids:
        description: 'Comma-separated list of run ids'
        required: false

jobs:
  get_workflow_info:
    runs-on: ubuntu-latest
    environment: GAS_URL
    defaults:
      run:
        working-directory: .github/workflows/scripts/github-interactions
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci --omit=dev

      - name: Get Workflow run ids by workflow_dispatch with run_ids # ワークフロー実行でワークフロー実行番号が指定された場合はその番号を取得する
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.run_ids
        run: echo "RUN_IDS=${{ github.event.inputs.run_ids || '-1' }}" >> $GITHUB_ENV
      - name: Get Workflow run ids by workflow_run # ワークフローがトリガーされた時は該当のトリガー元のワークフロー実行番号を取得する
        if: github.event_name == 'workflow_run'
        run: echo "RUN_IDS=${{ github.event.workflow_run.id || '-1' }}" >> $GITHUB_ENV
      - name: echo input RUN_IDS　
        run: echo $RUN_IDS

      - name: Set repository owner and name as env
        run: |
          echo "GITHUB_REPO_OWNER=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 1)" >> $GITHUB_ENV
          echo "GITHUB_REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)" >> $GITHUB_ENV

      - name: Run get-workflow
        run: npm run start:workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEPLOYMENT_FREQUENCY_URL: ${{ secrets.DEPLOYMENT_FREQUENCY_URL }}
